# Generated by Django 4.2.7 on 2024-02-12 07:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_name', unique=True),
        ),
    ]
